import type { Goal } from '../../types';

export const mockGoals: Goal[] = [
  {
    id: 'goal-calculus-exam',
    workspaceId: 'workspace-calculus-ii',
    text: 'Be ready to explain and solve every integration technique on the December final.',
    state: 'Guiding',
    inferred: {
      deadline: 'December 12',
      masteryType: 'Explain and solve independently',
      conceptScope: 87,
      pacing: 'Four focused sessions each week',
      tools: ['Practice', 'Visualizer', 'Tutor'],
    },
    previousText: 'Pass the Calculus II final in December.',
    createdAt: '2026-08-18T13:00:00.000Z',
    updatedAt: '2026-08-26T17:30:00.000Z',
  },
  {
    id: 'goal-calculus-midterm',
    workspaceId: 'workspace-calculus-ii',
    text: 'Shift to series and convergence after the integration exam.',
    state: 'Waiting',
    inferred: { deadline: 'October 21', conceptScope: 24, pacing: 'Begins after September 30' },
    createdAt: '2026-08-20T15:00:00.000Z',
    updatedAt: '2026-08-20T15:00:00.000Z',
  },
  {
    id: 'goal-calculus-substitution',
    workspaceId: 'workspace-calculus-ii',
    text: 'Use substitution reliably without relying on a formula sheet.',
    state: 'Met',
    inferred: { masteryType: 'Solve independently', conceptScope: 8 },
    achievedSummary: 'Solved mixed substitution sets accurately across three sessions.',
    createdAt: '2026-07-02T12:00:00.000Z',
    updatedAt: '2026-08-02T12:00:00.000Z',
  },
  {
    id: 'goal-calculus-applications',
    workspaceId: 'workspace-calculus-ii',
    text: 'Connect integration methods to physical applications.',
    state: 'Resting',
    inferred: { conceptScope: 17, tools: ['Visualizer'] },
    createdAt: '2026-07-15T12:00:00.000Z',
    updatedAt: '2026-08-10T12:00:00.000Z',
  },
  {
    id: 'goal-linear-algebra-proof',
    workspaceId: 'workspace-linear-algebra',
    text: 'Write clear proofs about vector spaces and linear maps.',
    state: 'Guiding',
    inferred: { masteryType: 'Explain and prove', pacing: 'Three sessions each week' },
    createdAt: '2026-08-10T12:00:00.000Z',
    updatedAt: '2026-08-22T12:00:00.000Z',
  },
  {
    id: 'goal-physics-review',
    workspaceId: 'workspace-physics',
    text: 'Retain the mechanics ideas needed for electromagnetism.',
    state: 'Guiding',
    inferred: { masteryType: 'Recall and apply', pacing: 'Monthly refresher' },
    createdAt: '2026-01-12T12:00:00.000Z',
    updatedAt: '2026-05-12T12:00:00.000Z',
  },
];
